author: "Christian Seiler"
author_url: http://www.christianseiler.ch
copyright: Christian Seiler Services

module: BundleManager
module_version: 1.0.0

swift_build_tool: spm
swift_version: 5
source_directory: ./Sources

