name: Swift

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Versions
      run: |
        swift --version
        swift package --version
        swift package tools-version
    - name: Resolve Dependencies
      run: swift package resolve
    - name: Run Build
      run: swift build -v
    - name: Run Tests
      run: swift test -v
